export const API = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
  },
  championships: {
    base: '/championships',
    byId: (id: string) => `/championships/${id}`,
    matches: (id: string) => `/championships/${id}/matches`,
    fixtures: (id: string) => `/championships/${id}/generate-fixtures`,
    standings: (id: string) => `/championships/${id}/standings`,
    statistics: (id: string, type: string) => `/championships/${id}/statistics/${type}`,
    report: (id: string) => `/championships/${id}/statistics/report`,
  },
  teams: {
    base: '/teams',
    byId: (id: string) => `/teams/${id}`,
    players: (teamId: string) => `/teams/${teamId}/players`,
    playerById: (teamId: string, playerId: string) => `/teams/${teamId}/players/${playerId}`,
    staff: (teamId: string) => `/teams/${teamId}/staff`,
  },
  matches: {
    start: (id: string) => `/matches/${id}/start`,
    conclude: (id: string) => `/matches/${id}/conclude`,
    events: (id: string) => `/matches/${id}/events`,
  },
  registrations: {
    base: '/registrations',
    byId: (id: string) => `/registrations/${id}`,
    approve: (id: string) => `/registrations/${id}/approve`,
    reject: (id: string) => `/registrations/${id}/reject`,
    documents: (id: string) => `/registrations/${id}/documents`,
  },
  payments: {
    base: '/payments',
    refund: (id: string) => `/payments/${id}/refund`,
    ledger: (championshipId: string) => `/payments/ledger/${championshipId}`,
  },
  cms: {
    articles: '/articles',
    galleries: '/galleries',
    videos: '/videos',
  },
  judges: {
    base: '/judges',
    byId: (id: string) => `/judges/${id}`,
  },
  disciplinary: {
    list: (champId: string, status?: string) =>
      `/championships/${champId}/suspensions${status ? `?status=${status}` : ''}`,
    create: (champId: string) => `/championships/${champId}/suspensions`,
    serve: (champId: string, id: string) => `/championships/${champId}/suspensions/${id}/serve`,
    cancel: (champId: string, id: string) => `/championships/${champId}/suspensions/${id}`,
  },
  polls: {
    list: (champId: string) => `/championships/${champId}/polls`,
    create: (champId: string) => `/championships/${champId}/polls`,
    results: (champId: string, pollId: string) => `/championships/${champId}/polls/${pollId}/results`,
    publish: (champId: string, pollId: string) => `/championships/${champId}/polls/${pollId}/publish`,
    close: (champId: string, pollId: string) => `/championships/${champId}/polls/${pollId}/close`,
    vote: (champId: string, pollId: string) => `/championships/${champId}/polls/${pollId}/vote`,
  },
  rankings: {
    list: (champId: string) => `/championships/${champId}/statistics/rankings`,
    create: (champId: string) => `/championships/${champId}/statistics/rankings`,
    compute: (champId: string, rankingId: string) => `/championships/${champId}/statistics/rankings/${rankingId}/compute`,
    delete: (champId: string, rankingId: string) => `/championships/${champId}/statistics/rankings/${rankingId}`,
  },
  expenses: {
    list: (champId?: string) => `/payments/expenses${champId ? `?championshipId=${champId}` : ''}`,
    create: '/payments/expenses',
    delete: (id: string) => `/payments/expenses/${id}`,
    dashboard: (champId: string) => `/payments/dashboard/${champId}`,
  },
  standings: {
    byChampionship: (champId: string) => `/championships/${champId}/standings`,
    full: (champId: string) => `/championships/${champId}/standings/full`,
    extraPoints: (champId: string, teamId: string) => `/championships/${champId}/standings/${teamId}/extra-points`,
  },
  structure: {
    phases: (id: string) => `/championships/${id}/phases`,
    phaseById: (id: string, phaseId: string) => `/championships/${id}/phases/${phaseId}`,
    rounds: (id: string) => `/championships/${id}/rounds`,
    roundById: (id: string, roundId: string) => `/championships/${id}/rounds/${roundId}`,
    matches: (id: string, roundId: string) => `/championships/${id}/rounds/${roundId}/matches`,
    matchById: (id: string, roundId: string, matchId: string) =>
      `/championships/${id}/rounds/${roundId}/matches/${matchId}`,
  },
  sumula: {
    get: (matchId: string) => `/matches/${matchId}/sumula`,
    open: (matchId: string) => `/matches/${matchId}/sumula`,
    close: (matchId: string) => `/matches/${matchId}/sumula/close`,
    lineup: (matchId: string) => `/matches/${matchId}/sumula/lineup`,
    removeLineup: (matchId: string, lineupId: string) => `/matches/${matchId}/sumula/lineup/${lineupId}`,
    officials: (matchId: string) => `/matches/${matchId}/sumula/officials`,
    observations: (matchId: string) => `/matches/${matchId}/sumula/observations`,
  },
} as const
